# TLDR
This notebook will start by importing my SQL module which automatically runs and intiates the SQL prereqs for Jupyter notebooks
so I will not have to do it each time. 
Next I will make a table of 25 rap artists with certain characteristics I deemed to be easy to visualize, this data is inspired by data I believe Spotify would measure

In [1]:
import SQL
SQL.import_SQL()

Requirement already satisfied: ipython-sql in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (0.5.0)
Requirement already satisfied: prettytable in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython-sql) (3.7.0)
Requirement already satisfied: ipython in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython-sql) (8.2.0)
Requirement already satisfied: sqlalchemy>=2.0 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython-sql) (2.0.12)
Requirement already satisfied: sqlparse in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython-sql) (0.4.4)
Requirement already satisfied: six in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)
Requirement already satisfied: backcall in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: decorator in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (0.1.2)
Requirement already satisfied: pickleshare in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: pygments>=2.4.0 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: setuptools>=18.5 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (61.2.0)
Requirement already satisfied: stack-data in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: pexpect>4.3 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (4.8.0)
Requirement already satisfied: appnope in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from ipython->ipython-sql) (0.1.2)
Requirement already satisfied: wcwidth in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in /Users/shannoningram/opt/anaconda3/lib/python3.9/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [2]:
%load_ext sql
%sql sqlite://

In [3]:
%%sql
CREATE TABLE Rapper (
    id INT PRIMARY KEY,
    artist_name VARCHAR(100),
    followers INT,
    popularity INT,
    monthly_listeners INT,
    total_tracks INT,
    explicit BOOLEAN,
    release_date DATE,
    duration_ms INT,
    danceability FLOAT,
    energy FLOAT,
    instrumentalness FLOAT,
    loudness FLOAT,
    speechiness FLOAT,
    valence FLOAT
);

 * sqlite://
Done.

[]

In [4]:
%%sql
INSERT INTO Rapper (id, artist_name, followers, popularity, monthly_listeners, total_tracks, explicit, release_date, duration_ms, danceability, energy, instrumentalness, loudness, speechiness, valence) 
VALUES
(1, 'Kendrick Lamar', 10245745, 86, 18754560, 81, TRUE, '2005-01-01', 235000, 0.78, 0.81, 0.05, -6.2, 0.3, 0.72),
(2, 'J. Cole', 8432169, 89, 15521532, 73, TRUE, '2007-01-01', 245000, 0.73, 0.83, 0.01, -5.8, 0.35, 0.68),
(3, 'Travis Scott', 16382153, 95, 27875423, 72, TRUE, '2010-01-01', 220000, 0.82, 0.88, 0.02, -4.5, 0.4, 0.75),
(4, 'Drake', 41547651, 96, 56478932, 173, TRUE, '2006-01-01', 210000, 0.79, 0.85, 0.01, -5.1, 0.32, 0.69),
(5, 'Eminem', 31375991, 92, 49874123, 263, TRUE, '1996-01-01', 248000, 0.68, 0.89, 0.03, -5.4, 0.39, 0.62),
(6, 'Cardi B', 14826523, 87, 27654135, 32, TRUE, '2015-01-01', 225000, 0.85, 0.86, 0.01, -4.8, 0.45, 0.82),
(7, 'Lil Wayne', 17934729, 85, 32469857, 298, TRUE, '1999-01-01', 238000, 0.77, 0.82, 0.03, -5.6, 0.33, 0.71),
(8, 'Kanye West', 21361985, 93, 38975462, 109, TRUE, '2000-01-01', 215000, 0.76, 0.87, 0.01, -5.3, 0.32, 0.68),
(9, 'Post Malone', 29184029, 94, 45298741, 64, TRUE, '2014-01-01', 210000, 0.77, 0.81, 0.1, -2.3, 0.52, 0.88),
(10, 'Migos', 8274312, 85, 15824653, 63, TRUE, '2011-01-01', 230000, 0.88, 0.89, 0.01, -5.2, 0.29, 0.73),
(11, 'Lil Uzi Vert', 11453987, 88, 21159845, 43, TRUE, '2013-01-01', 215000, 0.84, 0.87, 0.01, -5.4, 0.42, 0.78),
(12, 'Future', 15687321, 87, 26598741, 167, TRUE, '2010-01-01', 225000, 0.77, 0.86, 0.02, -5.3, 0.35, 0.67),
(13, 'Lil Baby', 9896543, 90, 18975214, 38, TRUE, '2017-01-01', 220000, 0.85, 0.88, 0.01, -4.9, 0.34, 0.73),
(14, 'Nicki Minaj', 16743165, 83, 29478135, 132, TRUE, '2007-01-01', 225000, 0.78, 0.84, 0.01, -5.7, 0.36, 0.69),
(15, 'A$AP Rocky', 8523698, 86, 15789362, 72, TRUE, '2011-01-01', 215000, 0.81, 0.88, 0.03, -5.2, 0.36, 0.74),
(16, 'Juice WRLD', 10657489, 91, 20987462, 45, TRUE, '2015-01-01', 240000, 0.77, 0.82, 0.01, -6.1, 0.45, 0.68),
(17, '21 Savage', 9587246, 89, 18259741, 39, TRUE, '2013-01-01', 230000, 0.82, 0.87, 0.02, -5.6, 0.35, 0.71),
(18, 'Kodak Black', 6759823, 84, 13589741, 49, TRUE, '2014-01-01', 240000, 0.79, 0.85, 0.02, -5.5, 0.32, 0.66),
(19, 'Meek Mill', 8246392, 85, 15742562, 86, TRUE, '2008-01-01', 220000, 0.78, 0.86, 0.02, -5.2, 0.36, 0.73),
(20, 'G-Eazy', 6874125, 84, 13256897, 75, TRUE, '2009-01-01', 230000, 0.78, 0.86, 0.03, -5.2, 0.31, 0.66),
(21, 'Logic', 6234987, 82, 12054973, 89, TRUE, '2010-01-01', 225000, 0.77, 0.85, 0.02, -5.3, 0.34, 0.68),
(22, 'Big Sean', 8297514, 85, 16379842, 74, TRUE, '2007-01-01', 240000, 0.79, 0.88, 0.01, -5.1, 0.32, 0.69),
(23, 'Wiz Khalifa', 13459721, 87, 22587416, 123, TRUE, '2006-01-01', 220000, 0.75, 0.87, 0.02, -5.5, 0.35, 0.65),
(24, 'Ludacris', 6742396, 80, 12875362, 118, TRUE, '1999-01-01', 230000, 0.77, 0.86, 0.01, -6.0, 0.36, 0.70),
(25, 'Tyga', 5982713, 81, 11498273, 136, TRUE, '2007-01-01', 215000, 0.78, 0.88, 0.02, -5.4, 0.33, 0.68);

 * sqlite://
25 rows affected.

[]

In [5]:
%%sql
select * from Rapper

 * sqlite://
Done.

[(1, 'Kendrick Lamar', 10245745, 86, 18754560, 81, 1, '2005-01-01', 235000, 0.78, 0.81, 0.05, -6.2, 0.3, 0.72),
 (2, 'J. Cole', 8432169, 89, 15521532, 73, 1, '2007-01-01', 245000, 0.73, 0.83, 0.01, -5.8, 0.35, 0.68),
 (3, 'Travis Scott', 16382153, 95, 27875423, 72, 1, '2010-01-01', 220000, 0.82, 0.88, 0.02, -4.5, 0.4, 0.75),
 (4, 'Drake', 41547651, 96, 56478932, 173, 1, '2006-01-01', 210000, 0.79, 0.85, 0.01, -5.1, 0.32, 0.69),
 (5, 'Eminem', 31375991, 92, 49874123, 263, 1, '1996-01-01', 248000, 0.68, 0.89, 0.03, -5.4, 0.39, 0.62),
 (6, 'Cardi B', 14826523, 87, 27654135, 32, 1, '2015-01-01', 225000, 0.85, 0.86, 0.01, -4.8, 0.45, 0.82),
 (7, 'Lil Wayne', 17934729, 85, 32469857, 298, 1, '1999-01-01', 238000, 0.77, 0.82, 0.03, -5.6, 0.33, 0.71),
 (8, 'Kanye West', 21361985, 93, 38975462, 109, 1, '2000-01-01', 215000, 0.76, 0.87, 0.01, -5.3, 0.32, 0.68),
 (9, 'Post Malone', 29184029, 94, 45298741, 64, 1, '2014-01-01', 210000, 0.77, 0.81, 0.1, -2.3, 0.52, 0.88),
 (10, 'Migos', 8274312, 85, 15824653, 63, 1, '2011-01-01', 230000, 0.88, 0.89, 0.01, -5.2, 0.29, 0.73),
 (11, 'Lil Uzi Vert', 11453987, 88, 21159845, 43, 1, '2013-01-01', 215000, 0.84, 0.87, 0.01, -5.4, 0.42, 0.78),
 (12, 'Future', 15687321, 87, 26598741, 167, 1, '2010-01-01', 225000, 0.77, 0.86, 0.02, -5.3, 0.35, 0.67),
 (13, 'Lil Baby', 9896543, 90, 18975214, 38, 1, '2017-01-01', 220000, 0.85, 0.88, 0.01, -4.9, 0.34, 0.73),
 (14, 'Nicki Minaj', 16743165, 83, 29478135, 132, 1, '2007-01-01', 225000, 0.78, 0.84, 0.01, -5.7, 0.36, 0.69),
 (15, 'A$AP Rocky', 8523698, 86, 15789362, 72, 1, '2011-01-01', 215000, 0.81, 0.88, 0.03, -5.2, 0.36, 0.74),
 (16, 'Juice WRLD', 10657489, 91, 20987462, 45, 1, '2015-01-01', 240000, 0.77, 0.82, 0.01, -6.1, 0.45, 0.68),
 (17, '21 Savage', 9587246, 89, 18259741, 39, 1, '2013-01-01', 230000, 0.82, 0.87, 0.02, -5.6, 0.35, 0.71),
 (18, 'Kodak Black', 6759823, 84, 13589741, 49, 1, '2014-01-01', 240000, 0.79, 0.85, 0.02, -5.5, 0.32, 0.66),
 (19, 'Meek Mill', 8246392, 85, 15742562, 86, 1, '2008-01-01', 220000, 0.78, 0.86, 0.02, -5.2, 0.36, 0.73),
 (20, 'G-Eazy', 6874125, 84, 13256897, 75, 1, '2009-01-01', 230000, 0.78, 0.86, 0.03, -5.2, 0.31, 0.66),
 (21, 'Logic', 6234987, 82, 12054973, 89, 1, '2010-01-01', 225000, 0.77, 0.85, 0.02, -5.3, 0.34, 0.68),
 (22, 'Big Sean', 8297514, 85, 16379842, 74, 1, '2007-01-01', 240000, 0.79, 0.88, 0.01, -5.1, 0.32, 0.69),
 (23, 'Wiz Khalifa', 13459721, 87, 22587416, 123, 1, '2006-01-01', 220000, 0.75, 0.87, 0.02, -5.5, 0.35, 0.65),
 (24, 'Ludacris', 6742396, 80, 12875362, 118, 1, '1999-01-01', 230000, 0.77, 0.86, 0.01, -6.0, 0.36, 0.7),
 (25, 'Tyga', 5982713, 81, 11498273, 136, 1, '2007-01-01', 215000, 0.78, 0.88, 0.02, -5.4, 0.33, 0.68)]

This list wouldn't be right without one person, I believe I would get serious backlash for not including him

In [6]:
%%sql
INSERT INTO Rapper (id, artist_name, followers, popularity, monthly_listeners, total_tracks, explicit, release_date, duration_ms, danceability, energy, instrumentalness, loudness, speechiness, valence) 
VALUES
(26, 'XXXTentacion', 52497831, 97, 62518982, 331, TRUE, '2015-01-01', 250000, 0.65, 0.85, 0.01, -3.1, 0.44, 0.69);

 * sqlite://
1 rows affected.

[]

In [7]:
%%sql
select * from Rapper

 * sqlite://
Done.

[(1, 'Kendrick Lamar', 10245745, 86, 18754560, 81, 1, '2005-01-01', 235000, 0.78, 0.81, 0.05, -6.2, 0.3, 0.72),
 (2, 'J. Cole', 8432169, 89, 15521532, 73, 1, '2007-01-01', 245000, 0.73, 0.83, 0.01, -5.8, 0.35, 0.68),
 (3, 'Travis Scott', 16382153, 95, 27875423, 72, 1, '2010-01-01', 220000, 0.82, 0.88, 0.02, -4.5, 0.4, 0.75),
 (4, 'Drake', 41547651, 96, 56478932, 173, 1, '2006-01-01', 210000, 0.79, 0.85, 0.01, -5.1, 0.32, 0.69),
 (5, 'Eminem', 31375991, 92, 49874123, 263, 1, '1996-01-01', 248000, 0.68, 0.89, 0.03, -5.4, 0.39, 0.62),
 (6, 'Cardi B', 14826523, 87, 27654135, 32, 1, '2015-01-01', 225000, 0.85, 0.86, 0.01, -4.8, 0.45, 0.82),
 (7, 'Lil Wayne', 17934729, 85, 32469857, 298, 1, '1999-01-01', 238000, 0.77, 0.82, 0.03, -5.6, 0.33, 0.71),
 (8, 'Kanye West', 21361985, 93, 38975462, 109, 1, '2000-01-01', 215000, 0.76, 0.87, 0.01, -5.3, 0.32, 0.68),
 (9, 'Post Malone', 29184029, 94, 45298741, 64, 1, '2014-01-01', 210000, 0.77, 0.81, 0.1, -2.3, 0.52, 0.88),
 (10, 'Migos', 8274312, 85, 15824653, 63, 1, '2011-01-01', 230000, 0.88, 0.89, 0.01, -5.2, 0.29, 0.73),
 (11, 'Lil Uzi Vert', 11453987, 88, 21159845, 43, 1, '2013-01-01', 215000, 0.84, 0.87, 0.01, -5.4, 0.42, 0.78),
 (12, 'Future', 15687321, 87, 26598741, 167, 1, '2010-01-01', 225000, 0.77, 0.86, 0.02, -5.3, 0.35, 0.67),
 (13, 'Lil Baby', 9896543, 90, 18975214, 38, 1, '2017-01-01', 220000, 0.85, 0.88, 0.01, -4.9, 0.34, 0.73),
 (14, 'Nicki Minaj', 16743165, 83, 29478135, 132, 1, '2007-01-01', 225000, 0.78, 0.84, 0.01, -5.7, 0.36, 0.69),
 (15, 'A$AP Rocky', 8523698, 86, 15789362, 72, 1, '2011-01-01', 215000, 0.81, 0.88, 0.03, -5.2, 0.36, 0.74),
 (16, 'Juice WRLD', 10657489, 91, 20987462, 45, 1, '2015-01-01', 240000, 0.77, 0.82, 0.01, -6.1, 0.45, 0.68),
 (17, '21 Savage', 9587246, 89, 18259741, 39, 1, '2013-01-01', 230000, 0.82, 0.87, 0.02, -5.6, 0.35, 0.71),
 (18, 'Kodak Black', 6759823, 84, 13589741, 49, 1, '2014-01-01', 240000, 0.79, 0.85, 0.02, -5.5, 0.32, 0.66),
 (19, 'Meek Mill', 8246392, 85, 15742562, 86, 1, '2008-01-01', 220000, 0.78, 0.86, 0.02, -5.2, 0.36, 0.73),
 (20, 'G-Eazy', 6874125, 84, 13256897, 75, 1, '2009-01-01', 230000, 0.78, 0.86, 0.03, -5.2, 0.31, 0.66),
 (21, 'Logic', 6234987, 82, 12054973, 89, 1, '2010-01-01', 225000, 0.77, 0.85, 0.02, -5.3, 0.34, 0.68),
 (22, 'Big Sean', 8297514, 85, 16379842, 74, 1, '2007-01-01', 240000, 0.79, 0.88, 0.01, -5.1, 0.32, 0.69),
 (23, 'Wiz Khalifa', 13459721, 87, 22587416, 123, 1, '2006-01-01', 220000, 0.75, 0.87, 0.02, -5.5, 0.35, 0.65),
 (24, 'Ludacris', 6742396, 80, 12875362, 118, 1, '1999-01-01', 230000, 0.77, 0.86, 0.01, -6.0, 0.36, 0.7),
 (25, 'Tyga', 5982713, 81, 11498273, 136, 1, '2007-01-01', 215000, 0.78, 0.88, 0.02, -5.4, 0.33, 0.68),
 (26, 'XXXTentacion', 52497831, 97, 62518982, 331, 1, '2015-01-01', 250000, 0.65, 0.85, 0.01, -3.1, 0.44, 0.69)]

Here we can see that 99% of rappers are already explicit so that column is really unecessary and tells us no new information

In [8]:
%%sql
ALTER TABLE Rapper
DROP COLUMN explicit;

 * sqlite://
Done.

[]

In [9]:
%%sql 
select * from Rapper

 * sqlite://
Done.

[(1, 'Kendrick Lamar', 10245745, 86, 18754560, 81, '2005-01-01', 235000, 0.78, 0.81, 0.05, -6.2, 0.3, 0.72),
 (2, 'J. Cole', 8432169, 89, 15521532, 73, '2007-01-01', 245000, 0.73, 0.83, 0.01, -5.8, 0.35, 0.68),
 (3, 'Travis Scott', 16382153, 95, 27875423, 72, '2010-01-01', 220000, 0.82, 0.88, 0.02, -4.5, 0.4, 0.75),
 (4, 'Drake', 41547651, 96, 56478932, 173, '2006-01-01', 210000, 0.79, 0.85, 0.01, -5.1, 0.32, 0.69),
 (5, 'Eminem', 31375991, 92, 49874123, 263, '1996-01-01', 248000, 0.68, 0.89, 0.03, -5.4, 0.39, 0.62),
 (6, 'Cardi B', 14826523, 87, 27654135, 32, '2015-01-01', 225000, 0.85, 0.86, 0.01, -4.8, 0.45, 0.82),
 (7, 'Lil Wayne', 17934729, 85, 32469857, 298, '1999-01-01', 238000, 0.77, 0.82, 0.03, -5.6, 0.33, 0.71),
 (8, 'Kanye West', 21361985, 93, 38975462, 109, '2000-01-01', 215000, 0.76, 0.87, 0.01, -5.3, 0.32, 0.68),
 (9, 'Post Malone', 29184029, 94, 45298741, 64, '2014-01-01', 210000, 0.77, 0.81, 0.1, -2.3, 0.52, 0.88),
 (10, 'Migos', 8274312, 85, 15824653, 63, '2011-01-01', 230000, 0.88, 0.89, 0.01, -5.2, 0.29, 0.73),
 (11, 'Lil Uzi Vert', 11453987, 88, 21159845, 43, '2013-01-01', 215000, 0.84, 0.87, 0.01, -5.4, 0.42, 0.78),
 (12, 'Future', 15687321, 87, 26598741, 167, '2010-01-01', 225000, 0.77, 0.86, 0.02, -5.3, 0.35, 0.67),
 (13, 'Lil Baby', 9896543, 90, 18975214, 38, '2017-01-01', 220000, 0.85, 0.88, 0.01, -4.9, 0.34, 0.73),
 (14, 'Nicki Minaj', 16743165, 83, 29478135, 132, '2007-01-01', 225000, 0.78, 0.84, 0.01, -5.7, 0.36, 0.69),
 (15, 'A$AP Rocky', 8523698, 86, 15789362, 72, '2011-01-01', 215000, 0.81, 0.88, 0.03, -5.2, 0.36, 0.74),
 (16, 'Juice WRLD', 10657489, 91, 20987462, 45, '2015-01-01', 240000, 0.77, 0.82, 0.01, -6.1, 0.45, 0.68),
 (17, '21 Savage', 9587246, 89, 18259741, 39, '2013-01-01', 230000, 0.82, 0.87, 0.02, -5.6, 0.35, 0.71),
 (18, 'Kodak Black', 6759823, 84, 13589741, 49, '2014-01-01', 240000, 0.79, 0.85, 0.02, -5.5, 0.32, 0.66),
 (19, 'Meek Mill', 8246392, 85, 15742562, 86, '2008-01-01', 220000, 0.78, 0.86, 0.02, -5.2, 0.36, 0.73),
 (20, 'G-Eazy', 6874125, 84, 13256897, 75, '2009-01-01', 230000, 0.78, 0.86, 0.03, -5.2, 0.31, 0.66),
 (21, 'Logic', 6234987, 82, 12054973, 89, '2010-01-01', 225000, 0.77, 0.85, 0.02, -5.3, 0.34, 0.68),
 (22, 'Big Sean', 8297514, 85, 16379842, 74, '2007-01-01', 240000, 0.79, 0.88, 0.01, -5.1, 0.32, 0.69),
 (23, 'Wiz Khalifa', 13459721, 87, 22587416, 123, '2006-01-01', 220000, 0.75, 0.87, 0.02, -5.5, 0.35, 0.65),
 (24, 'Ludacris', 6742396, 80, 12875362, 118, '1999-01-01', 230000, 0.77, 0.86, 0.01, -6.0, 0.36, 0.7),
 (25, 'Tyga', 5982713, 81, 11498273, 136, '2007-01-01', 215000, 0.78, 0.88, 0.02, -5.4, 0.33, 0.68),
 (26, 'XXXTentacion', 52497831, 97, 62518982, 331, '2015-01-01', 250000, 0.65, 0.85, 0.01, -3.1, 0.44, 0.69)]

Here I realize that alot of these columns are not really useful but I want to keep them in a backup table and drop them from the table that I'll play with. So I'll create a duplicate and remove more columns from that duplicate

In [10]:
%%sql
CREATE TABLE Rapper_Backup AS
SELECT * FROM Rapper;

 * sqlite://
Done.

[]

In [11]:
%%sql
ALTER TABLE Rapper
DROP COLUMN speechiness;

ALTER TABLE Rapper
DROP COLUMN valence;

select * from Rapper;

 * sqlite://
Done.
Done.
Done.

[(1, 'Kendrick Lamar', 10245745, 86, 18754560, 81, '2005-01-01', 235000, 0.78, 0.81, 0.05, -6.2),
 (2, 'J. Cole', 8432169, 89, 15521532, 73, '2007-01-01', 245000, 0.73, 0.83, 0.01, -5.8),
 (3, 'Travis Scott', 16382153, 95, 27875423, 72, '2010-01-01', 220000, 0.82, 0.88, 0.02, -4.5),
 (4, 'Drake', 41547651, 96, 56478932, 173, '2006-01-01', 210000, 0.79, 0.85, 0.01, -5.1),
 (5, 'Eminem', 31375991, 92, 49874123, 263, '1996-01-01', 248000, 0.68, 0.89, 0.03, -5.4),
 (6, 'Cardi B', 14826523, 87, 27654135, 32, '2015-01-01', 225000, 0.85, 0.86, 0.01, -4.8),
 (7, 'Lil Wayne', 17934729, 85, 32469857, 298, '1999-01-01', 238000, 0.77, 0.82, 0.03, -5.6),
 (8, 'Kanye West', 21361985, 93, 38975462, 109, '2000-01-01', 215000, 0.76, 0.87, 0.01, -5.3),
 (9, 'Post Malone', 29184029, 94, 45298741, 64, '2014-01-01', 210000, 0.77, 0.81, 0.1, -2.3),
 (10, 'Migos', 8274312, 85, 15824653, 63, '2011-01-01', 230000, 0.88, 0.89, 0.01, -5.2),
 (11, 'Lil Uzi Vert', 11453987, 88, 21159845, 43, '2013-01-01', 215000, 0.84, 0.87, 0.01, -5.4),
 (12, 'Future', 15687321, 87, 26598741, 167, '2010-01-01', 225000, 0.77, 0.86, 0.02, -5.3),
 (13, 'Lil Baby', 9896543, 90, 18975214, 38, '2017-01-01', 220000, 0.85, 0.88, 0.01, -4.9),
 (14, 'Nicki Minaj', 16743165, 83, 29478135, 132, '2007-01-01', 225000, 0.78, 0.84, 0.01, -5.7),
 (15, 'A$AP Rocky', 8523698, 86, 15789362, 72, '2011-01-01', 215000, 0.81, 0.88, 0.03, -5.2),
 (16, 'Juice WRLD', 10657489, 91, 20987462, 45, '2015-01-01', 240000, 0.77, 0.82, 0.01, -6.1),
 (17, '21 Savage', 9587246, 89, 18259741, 39, '2013-01-01', 230000, 0.82, 0.87, 0.02, -5.6),
 (18, 'Kodak Black', 6759823, 84, 13589741, 49, '2014-01-01', 240000, 0.79, 0.85, 0.02, -5.5),
 (19, 'Meek Mill', 8246392, 85, 15742562, 86, '2008-01-01', 220000, 0.78, 0.86, 0.02, -5.2),
 (20, 'G-Eazy', 6874125, 84, 13256897, 75, '2009-01-01', 230000, 0.78, 0.86, 0.03, -5.2),
 (21, 'Logic', 6234987, 82, 12054973, 89, '2010-01-01', 225000, 0.77, 0.85, 0.02, -5.3),
 (22, 'Big Sean', 8297514, 85, 16379842, 74, '2007-01-01', 240000, 0.79, 0.88, 0.01, -5.1),
 (23, 'Wiz Khalifa', 13459721, 87, 22587416, 123, '2006-01-01', 220000, 0.75, 0.87, 0.02, -5.5),
 (24, 'Ludacris', 6742396, 80, 12875362, 118, '1999-01-01', 230000, 0.77, 0.86, 0.01, -6.0),
 (25, 'Tyga', 5982713, 81, 11498273, 136, '2007-01-01', 215000, 0.78, 0.88, 0.02, -5.4),
 (26, 'XXXTentacion', 52497831, 97, 62518982, 331, '2015-01-01', 250000, 0.65, 0.85, 0.01, -3.1)]

I'm going to add a column for grammy wins and Billboard Hot 100 number 1's. Please note these are not accurate nor are they up to date. All of these are fake numbers

In [12]:
%%sql
alter table Rapper
add column Grammys INT;

 * sqlite://
Done.

[]

In [13]:
%%sql
alter table Rapper
add column no1 INT;

 * sqlite://
Done.

[]

In [17]:
%%sql
UPDATE Rapper
set Grammys = CASE artist_name
    WHEN 'Kendrick Lamar' then 13
    WHEN 'Drake' then 4
    WHEN 'Eminem' then 15
    WHEN 'Cardi B' then 1
    WHEN 'Lil Wayne' then 5
    WHEN 'Kanye West' then 22
    WHEN 'Future' then 1
    WHEN 'Nicki Minaj' then 1
    WHEN 'Ludacris' then 3
    WHEN 'Wiz Khalifa' then 1
    ELSE 0
    END;

 * sqlite://
26 rows affected.

[]

In [19]:
%%sql
UPDATE Rapper
set no1 = CASE popularity
    WHEN popularity >= 96 THEN 2
    else 0
END;

 * sqlite://
26 rows affected.

[]

In [20]:
%%sql
select * from Rapper;

 * sqlite://
Done.

[(1, 'Kendrick Lamar', 10245745, 86, 18754560, 81, '2005-01-01', 235000, 0.78, 0.81, 0.05, -6.2, 13, 0),
 (2, 'J. Cole', 8432169, 89, 15521532, 73, '2007-01-01', 245000, 0.73, 0.83, 0.01, -5.8, 0, 0),
 (3, 'Travis Scott', 16382153, 95, 27875423, 72, '2010-01-01', 220000, 0.82, 0.88, 0.02, -4.5, 0, 0),
 (4, 'Drake', 41547651, 96, 56478932, 173, '2006-01-01', 210000, 0.79, 0.85, 0.01, -5.1, 4, 0),
 (5, 'Eminem', 31375991, 92, 49874123, 263, '1996-01-01', 248000, 0.68, 0.89, 0.03, -5.4, 15, 0),
 (6, 'Cardi B', 14826523, 87, 27654135, 32, '2015-01-01', 225000, 0.85, 0.86, 0.01, -4.8, 1, 0),
 (7, 'Lil Wayne', 17934729, 85, 32469857, 298, '1999-01-01', 238000, 0.77, 0.82, 0.03, -5.6, 5, 0),
 (8, 'Kanye West', 21361985, 93, 38975462, 109, '2000-01-01', 215000, 0.76, 0.87, 0.01, -5.3, 22, 0),
 (9, 'Post Malone', 29184029, 94, 45298741, 64, '2014-01-01', 210000, 0.77, 0.81, 0.1, -2.3, 0, 0),
 (10, 'Migos', 8274312, 85, 15824653, 63, '2011-01-01', 230000, 0.88, 0.89, 0.01, -5.2, 0, 0),
 (11, 'Lil Uzi Vert', 11453987, 88, 21159845, 43, '2013-01-01', 215000, 0.84, 0.87, 0.01, -5.4, 0, 0),
 (12, 'Future', 15687321, 87, 26598741, 167, '2010-01-01', 225000, 0.77, 0.86, 0.02, -5.3, 1, 0),
 (13, 'Lil Baby', 9896543, 90, 18975214, 38, '2017-01-01', 220000, 0.85, 0.88, 0.01, -4.9, 0, 0),
 (14, 'Nicki Minaj', 16743165, 83, 29478135, 132, '2007-01-01', 225000, 0.78, 0.84, 0.01, -5.7, 1, 0),
 (15, 'A$AP Rocky', 8523698, 86, 15789362, 72, '2011-01-01', 215000, 0.81, 0.88, 0.03, -5.2, 0, 0),
 (16, 'Juice WRLD', 10657489, 91, 20987462, 45, '2015-01-01', 240000, 0.77, 0.82, 0.01, -6.1, 0, 0),
 (17, '21 Savage', 9587246, 89, 18259741, 39, '2013-01-01', 230000, 0.82, 0.87, 0.02, -5.6, 0, 0),
 (18, 'Kodak Black', 6759823, 84, 13589741, 49, '2014-01-01', 240000, 0.79, 0.85, 0.02, -5.5, 0, 0),
 (19, 'Meek Mill', 8246392, 85, 15742562, 86, '2008-01-01', 220000, 0.78, 0.86, 0.02, -5.2, 0, 0),
 (20, 'G-Eazy', 6874125, 84, 13256897, 75, '2009-01-01', 230000, 0.78, 0.86, 0.03, -5.2, 0, 0),
 (21, 'Logic', 6234987, 82, 12054973, 89, '2010-01-01', 225000, 0.77, 0.85, 0.02, -5.3, 0, 0),
 (22, 'Big Sean', 8297514, 85, 16379842, 74, '2007-01-01', 240000, 0.79, 0.88, 0.01, -5.1, 0, 0),
 (23, 'Wiz Khalifa', 13459721, 87, 22587416, 123, '2006-01-01', 220000, 0.75, 0.87, 0.02, -5.5, 1, 0),
 (24, 'Ludacris', 6742396, 80, 12875362, 118, '1999-01-01', 230000, 0.77, 0.86, 0.01, -6.0, 3, 0),
 (25, 'Tyga', 5982713, 81, 11498273, 136, '2007-01-01', 215000, 0.78, 0.88, 0.02, -5.4, 0, 0),
 (26, 'XXXTentacion', 52497831, 97, 62518982, 331, '2015-01-01', 250000, 0.65, 0.85, 0.01, -3.1, 0, 0)]